// Mock data — replace with real API calls once backend is wired

export const mockIndexers = [
  {
    id: 1,
    name: "1337x",
    enable: true,
    protocol: "torrent",
    privacy: "public",
    capabilities: { categories: ["Movies", "TV", "Music", "Games"] },
    stats: {
      numberOfQueries: 2341,
      numberOfFailedQueries: 18,
      numberOfGrabs: 312,
      averageResponseTime: 420,
    },
  },
  {
    id: 2,
    name: "YGGTorrent",
    enable: true,
    protocol: "torrent",
    privacy: "private",
    capabilities: { categories: ["Movies", "TV", "Ebooks"] },
    stats: {
      numberOfQueries: 1875,
      numberOfFailedQueries: 4,
      numberOfGrabs: 189,
      averageResponseTime: 310,
    },
  },
  {
    id: 3,
    name: "RARBG Mirror",
    enable: false,
    protocol: "torrent",
    privacy: "public",
    capabilities: { categories: ["Movies", "TV", "Games"] },
    stats: {
      numberOfQueries: 0,
      numberOfFailedQueries: 0,
      numberOfGrabs: 0,
      averageResponseTime: 0,
    },
  },
  {
    id: 4,
    name: "NZBGeek",
    enable: true,
    protocol: "usenet",
    privacy: "private",
    capabilities: { categories: ["Movies", "TV", "Music"] },
    stats: {
      numberOfQueries: 934,
      numberOfFailedQueries: 92,
      numberOfGrabs: 76,
      averageResponseTime: 890,
    },
  },
  {
    id: 5,
    name: "The Pirate Bay",
    enable: true,
    protocol: "torrent",
    privacy: "public",
    capabilities: { categories: ["Movies", "TV", "Music", "Software"] },
    stats: {
      numberOfQueries: 3102,
      numberOfFailedQueries: 211,
      numberOfGrabs: 430,
      averageResponseTime: 1240,
    },
  },
  {
    id: 6,
    name: "Usenet.Farm",
    enable: true,
    protocol: "usenet",
    privacy: "private",
    capabilities: { categories: ["Movies", "TV", "Ebooks", "Music"] },
    stats: {
      numberOfQueries: 540,
      numberOfFailedQueries: 3,
      numberOfGrabs: 98,
      averageResponseTime: 275,
    },
  },
];

export const mockHistory = [
  {
    id: 1,
    date: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    query: "Dune Part Two 2160p",
    indexer: "1337x",
    eventType: "grab",
    successful: true,
    categories: ["Movies"],
    elapsedTime: 430,
  },
  {
    id: 2,
    date: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
    query: "Dune Part Two 2160p",
    indexer: "YGGTorrent",
    eventType: "indexerQuery",
    successful: true,
    categories: ["Movies"],
    elapsedTime: 315,
  },
  {
    id: 3,
    date: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    query: "The Bear S03",
    indexer: "1337x",
    eventType: "indexerQuery",
    successful: true,
    categories: ["TV"],
    elapsedTime: 508,
  },
  {
    id: 4,
    date: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    query: "Oppenheimer 4K HDR",
    indexer: "NZBGeek",
    eventType: "grab",
    successful: true,
    categories: ["Movies"],
    elapsedTime: 920,
  },
  {
    id: 5,
    date: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    query: "Shogun S01 Complete",
    indexer: "The Pirate Bay",
    eventType: "indexerQuery",
    successful: false,
    categories: ["TV"],
    elapsedTime: 5001,
  },
  {
    id: 6,
    date: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    query: "Poor Things 1080p",
    indexer: "Usenet.Farm",
    eventType: "indexerQuery",
    successful: true,
    categories: ["Movies"],
    elapsedTime: 280,
  },
  {
    id: 7,
    date: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    query: "Fallout S01 2160p",
    indexer: "YGGTorrent",
    eventType: "grab",
    successful: true,
    categories: ["TV"],
    elapsedTime: 340,
  },
  {
    id: 8,
    date: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    query: "Civil War 2024",
    indexer: "1337x",
    eventType: "indexerQuery",
    successful: true,
    categories: ["Movies"],
    elapsedTime: 455,
  },
];

// Mock search results keyed by query keyword for demo variety
export const mockSearchResults = [
  {
    guid: "r001",
    title: "Dune.Part.Two.2024.2160p.UHD.BluRay.x265.HDR.DTS-HD.MA-GROUP",
    indexer: "1337x",
    publishDate: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    size: 47244640256, // ~44 GB
    seeders: 312,
    leechers: 28,
    categories: ["Movies"],
    protocol: "torrent",
  },
  {
    guid: "r002",
    title: "Dune.Part.Two.2024.1080p.BluRay.x264-SPARKS",
    indexer: "YGGTorrent",
    publishDate: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
    size: 14763950080, // ~13.7 GB
    seeders: 891,
    leechers: 44,
    categories: ["Movies"],
    protocol: "torrent",
  },
  {
    guid: "r003",
    title: "Dune.Part.Two.2024.2160p.WEB-DL.DDP5.1.Atmos.DV.HDR10.H.265-FLUX",
    indexer: "NZBGeek",
    publishDate: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
    size: 22548578304, // ~21 GB
    seeders: null,
    leechers: null,
    categories: ["Movies"],
    protocol: "usenet",
  },
  {
    guid: "r004",
    title: "Dune.Part.Two.2024.720p.BluRay.x264",
    indexer: "The Pirate Bay",
    publishDate: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    size: 4831838208, // ~4.5 GB
    seeders: 1240,
    leechers: 110,
    categories: ["Movies"],
    protocol: "torrent",
  },
  {
    guid: "r005",
    title: "Dune.Part.Two.2024.2160p.UHD.BluRay.Remux.HDR.HEVC.TrueHD-NOGROUP",
    indexer: "Usenet.Farm",
    publishDate: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
    size: 85899345920, // ~80 GB
    seeders: null,
    leechers: null,
    categories: ["Movies"],
    protocol: "usenet",
  },
  {
    guid: "r006",
    title: "Dune.Part.Two.2024.1080p.WEB-DL.DD5.1.H.264-EVO",
    indexer: "1337x",
    publishDate: new Date(Date.now() - 6 * 24 * 3600 * 1000).toISOString(),
    size: 5905580032, // ~5.5 GB
    seeders: 456,
    leechers: 22,
    categories: ["Movies"],
    protocol: "torrent",
  },
];
